spring:
  profiles:
    active: '${SPRING_PROFILES_ACTIVE:local}'
  application:
    name: spring-shopping
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: '${DATASOURCE_HOST:jdbc:mysql://localhost:3306/shopping}'
    username: '${DATASOURCE_USERNAME:root}'
    password: '${DATASOURCE_PASSWORD:1234}'
    driver-class-name: '${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}'
  data:
    redis:
      host: '${REDIS_HOST:localhost}'
      port: '${REDIS_PORT:6379}'
service:
  abusing:
    url: '${SERVICE_ABUSING_URL:https://www.purgomalum.com/service/json?text=}'